// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0zkUrTF92nFZRCifsYHOFPxgU7x1Kqxg',
    appId: '1:684526639884:web:741af62713bbcda6b58729',
    messagingSenderId: '684526639884',
    projectId: 'redit-clone-e6550',
    authDomain: 'redit-clone-e6550.firebaseapp.com',
    storageBucket: 'redit-clone-e6550.firebasestorage.app',
    measurementId: 'G-ST6KE204JL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6OzMse3tXmzn-1402ug7ylK1n8VCMstU',
    appId: '1:684526639884:android:86be36e1130563d5b58729',
    messagingSenderId: '684526639884',
    projectId: 'redit-clone-e6550',
    storageBucket: 'redit-clone-e6550.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCSybHioWqFQaXRxm_wgEvWuSp6oL6Ia60',
    appId: '1:684526639884:ios:f1358ff7604106c1b58729',
    messagingSenderId: '684526639884',
    projectId: 'redit-clone-e6550',
    storageBucket: 'redit-clone-e6550.firebasestorage.app',
    iosBundleId: 'com.example.reditClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCSybHioWqFQaXRxm_wgEvWuSp6oL6Ia60',
    appId: '1:684526639884:ios:f1358ff7604106c1b58729',
    messagingSenderId: '684526639884',
    projectId: 'redit-clone-e6550',
    storageBucket: 'redit-clone-e6550.firebasestorage.app',
    iosBundleId: 'com.example.reditClone',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA0zkUrTF92nFZRCifsYHOFPxgU7x1Kqxg',
    appId: '1:684526639884:web:83a9720da9bc5b72b58729',
    messagingSenderId: '684526639884',
    projectId: 'redit-clone-e6550',
    authDomain: 'redit-clone-e6550.firebaseapp.com',
    storageBucket: 'redit-clone-e6550.firebasestorage.app',
    measurementId: 'G-4K8338D438',
  );
}
